name: Scrape Nikkei News

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:        # Allow manual trigger from GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python sony.py
